# Generated by Django 3.2.3 on 2021-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeogInfo',
            fields=[
                ('GeogCode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('timezone', models.CharField(blank=True, max_length=150, null=True)),
                ('current_date', models.DateField()),
                ('current_sunrise', models.DateField()),
                ('current_sunset', models.DateField()),
                ('current_temp', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'ordering': ['GeogCode_id'],
            },
        ),
    ]
